// GENERATED by scripts/gen_graph_order.py -- DO NOT EDIT BY HAND.
// Source of truth: the compiled pi0.5 QNN context binaries, read via
// qnn-context-binary-utility. Regenerate after any re-export:
//     scripts/dump-graph-io.sh && scripts/gen_graph_order.py
//
// Read this before touching the packing code:
//   * QrbInferenceManager::inference_execute() takes ONE flat byte buffer and
//     slices it across graph inputs in the order below. Wrong order == silently
//     wrong actions, no error, no crash.
//   * action_expert orders its KV inputs LEXICOGRAPHICALLY
//     (l0, l1, l10..l17, l2..l9) while backbone emits them NUMERICALLY
//     (l0..l17). A reorder between the two stages is mandatory.
//   * rope cos comes BEFORE sin in backbone and action_expert inputs, but
//     token_emb emits sin BEFORE cos. Another mandatory swap.
#ifndef QRB_ROS_VLA__PI05_GRAPH_ORDER_HPP_
#define QRB_ROS_VLA__PI05_GRAPH_ORDER_HPP_

#include <cstddef>
#include <cstdint>

namespace qrb_ros_vla
{
namespace pi05
{

struct TensorSpec
{
  const char * name;
  size_t elem_count;
  size_t byte_count;
};

// pi05_vision_encoder inputs: 1 tensors, 602112 bytes total
inline constexpr TensorSpec kVisionEncoderInputs[] = {
  {"image", 150528, 602112},  // [1x3x224x224] FLOAT_32
};
inline constexpr size_t kVisionEncoderInputsBytes = 602112;

// pi05_vision_encoder outputs: 1 tensors, 2097152 bytes total
inline constexpr TensorSpec kVisionEncoderOutputs[] = {
  {"img_embed", 524288, 2097152},  // [1x256x2048] FLOAT_32
};
inline constexpr size_t kVisionEncoderOutputsBytes = 2097152;

// pi05_token_emb inputs: 5 tensors, 6293056 bytes total
inline constexpr TensorSpec kTokenEmbInputs[] = {
  {"lang_tokens", 200, 800},  // [1x200] INT_32
  {"img_embed1", 524288, 2097152},  // [1x256x2048] FLOAT_32
  {"img_embed2", 524288, 2097152},  // [1x256x2048] FLOAT_32
  {"img_embed3", 524288, 2097152},  // [1x256x2048] FLOAT_32
  {"lang_mask", 200, 800},  // [1x200] FLOAT_32
};
inline constexpr size_t kTokenEmbInputsBytes = 6293056;

// pi05_token_emb outputs: 7 tensors, 12923984 bytes total
inline constexpr TensorSpec kTokenEmbOutputs[] = {
  {"prefix_emb", 1982464, 7929856},  // [1x968x2048] FLOAT_32
  {"prefix_att_2d", 937024, 3748096},  // [1x1x968x968] FLOAT_32
  {"prefix_sin", 123904, 495616},  // [1x968x1x128] FLOAT_32
  {"prefix_cos", 123904, 495616},  // [1x968x1x128] FLOAT_32
  {"suffix_sin", 6400, 25600},  // [1x50x1x128] FLOAT_32
  {"suffix_cos", 6400, 25600},  // [1x50x1x128] FLOAT_32
  {"full_att_4d", 50900, 203600},  // [1x1x50x1018] FLOAT_32
};
inline constexpr size_t kTokenEmbOutputsBytes = 12923984;

// pi05_backbone inputs: 4 tensors, 12669184 bytes total
inline constexpr TensorSpec kBackboneInputs[] = {
  {"prefix_att_2d_masks", 937024, 3748096},  // [1x1x968x968] FLOAT_32
  {"hidden_state", 1982464, 7929856},  // [1x968x2048] FLOAT_32
  {"rope_emb_cos", 123904, 495616},  // [1x968x1x128] FLOAT_32
  {"rope_emb_sin", 123904, 495616},  // [1x968x1x128] FLOAT_32
};
inline constexpr size_t kBackboneInputsBytes = 12669184;

// pi05_backbone outputs: 36 tensors, 35684352 bytes total
inline constexpr TensorSpec kBackboneOutputs[] = {
  {"k_cache_l0", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"k_cache_l1", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"k_cache_l2", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"k_cache_l3", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"k_cache_l4", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"k_cache_l5", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"k_cache_l6", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"k_cache_l7", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"k_cache_l8", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"k_cache_l9", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"k_cache_l10", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"k_cache_l11", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"k_cache_l12", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"k_cache_l13", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"k_cache_l14", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"k_cache_l15", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"k_cache_l16", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"k_cache_l17", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"v_cache_l0", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"v_cache_l1", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"v_cache_l2", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"v_cache_l3", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"v_cache_l4", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"v_cache_l5", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"v_cache_l6", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"v_cache_l7", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"v_cache_l8", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"v_cache_l9", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"v_cache_l10", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"v_cache_l11", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"v_cache_l12", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"v_cache_l13", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"v_cache_l14", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"v_cache_l15", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"v_cache_l16", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"v_cache_l17", 247808, 991232},  // [1x968x1x256] FLOAT_32
};
inline constexpr size_t kBackboneOutputsBytes = 35684352;

// pi05_action_expert inputs: 41 tensors, 35945556 bytes total
inline constexpr TensorSpec kActionExpertInputs[] = {
  {"x_t", 1600, 6400},  // [1x50x32] FLOAT_32
  {"time_step", 1, 4},  // [1] FLOAT_32
  {"key_cache_l0", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"key_cache_l1", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"key_cache_l10", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"key_cache_l11", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"key_cache_l12", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"key_cache_l13", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"key_cache_l14", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"key_cache_l15", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"key_cache_l16", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"key_cache_l17", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"key_cache_l2", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"key_cache_l3", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"key_cache_l4", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"key_cache_l5", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"key_cache_l6", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"key_cache_l7", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"key_cache_l8", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"key_cache_l9", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"value_cache_l0", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"value_cache_l1", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"value_cache_l10", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"value_cache_l11", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"value_cache_l12", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"value_cache_l13", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"value_cache_l14", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"value_cache_l15", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"value_cache_l16", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"value_cache_l17", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"value_cache_l2", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"value_cache_l3", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"value_cache_l4", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"value_cache_l5", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"value_cache_l6", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"value_cache_l7", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"value_cache_l8", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"value_cache_l9", 247808, 991232},  // [1x968x1x256] FLOAT_32
  {"rope_emb_cos", 6400, 25600},  // [1x50x1x128] FLOAT_32
  {"rope_emb_sin", 6400, 25600},  // [1x50x1x128] FLOAT_32
  {"full_att_4d", 50900, 203600},  // [1x1x50x1018] FLOAT_32
};
inline constexpr size_t kActionExpertInputsBytes = 35945556;

// pi05_action_expert outputs: 1 tensors, 6400 bytes total
inline constexpr TensorSpec kActionExpertOutputs[] = {
  {"action_emb", 1600, 6400},  // [1x50x32] FLOAT_32
};
inline constexpr size_t kActionExpertOutputsBytes = 6400;

}  // namespace pi05
}  // namespace qrb_ros_vla

#endif  // QRB_ROS_VLA__PI05_GRAPH_ORDER_HPP_
