#!/usr/bin/env python3
"""Generate pi05_graph_order.hpp from the context-binary JSON dumps.

Run scripts/dump-graph-io.sh first. The generated header is committed so the
build does not depend on having the 2.9 GB bundle present, but it is
regenerable — and *must* be regenerated if the bundle is re-exported with a
different QAIRT version, because graph tensor order is a compile-time artifact.

Usage: scripts/gen_graph_order.py [graph-io-dir] [output-header]
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

COMPONENTS = ("vision_encoder", "token_emb", "backbone", "action_expert")

DTYPE_BYTES = {
    "QNN_DATATYPE_FLOAT_32": 4,
    "QNN_DATATYPE_INT_32": 4,
    "QNN_DATATYPE_UINT_32": 4,
    "QNN_DATATYPE_FLOAT_16": 2,
    "QNN_DATATYPE_UFIXED_POINT_8": 1,
    "QNN_DATATYPE_SFIXED_POINT_8": 1,
}


def find_key(obj, key, depth=0):
    """Depth-first search for the first occurrence of `key`."""
    if depth > 8:
        return None
    if isinstance(obj, dict):
        if key in obj:
            return obj[key]
        for value in obj.values():
            found = find_key(value, key, depth + 1)
            if found is not None:
                return found
    elif isinstance(obj, list):
        for value in obj:
            found = find_key(value, key, depth + 1)
            if found is not None:
                return found
    return None


def tensors(graph_info, which):
    out = []
    for entry in graph_info.get(which) or []:
        info = entry.get("info", entry)
        dims = info["dimensions"]
        dtype = info["dataType"]
        count = 1
        for d in dims:
            count *= d
        out.append((info["name"], dims, dtype, count, count * DTYPE_BYTES[dtype]))
    return out


def main() -> int:
    src = Path(sys.argv[1] if len(sys.argv) > 1 else "bench/graph-io")
    dst = Path(
        sys.argv[2]
        if len(sys.argv) > 2
        else "ros2_ws/src/qrb_ros_vla/include/qrb_ros_vla/pi05_graph_order.hpp"
    )

    parsed = {}
    for comp in COMPONENTS:
        path = src / f"{comp}.json"
        if not path.exists():
            print(f"ERROR: {path} missing; run scripts/dump-graph-io.sh", file=sys.stderr)
            return 1
        graphs = find_key(json.loads(path.read_text()), "graphs")
        if not graphs:
            print(f"ERROR: no 'graphs' in {path}", file=sys.stderr)
            return 1
        info = graphs[0].get("info", graphs[0])
        parsed[comp] = {
            "name": info.get("graphName", comp),
            "inputs": tensors(info, "graphInputs"),
            "outputs": tensors(info, "graphOutputs"),
        }

    lines = [
        "// GENERATED by scripts/gen_graph_order.py -- DO NOT EDIT BY HAND.",
        "// Source of truth: the compiled pi0.5 QNN context binaries, read via",
        "// qnn-context-binary-utility. Regenerate after any re-export:",
        "//     scripts/dump-graph-io.sh && scripts/gen_graph_order.py",
        "//",
        "// Read this before touching the packing code:",
        "//   * QrbInferenceManager::inference_execute() takes ONE flat byte buffer and",
        "//     slices it across graph inputs in the order below. Wrong order == silently",
        "//     wrong actions, no error, no crash.",
        "//   * action_expert orders its KV inputs LEXICOGRAPHICALLY",
        "//     (l0, l1, l10..l17, l2..l9) while backbone emits them NUMERICALLY",
        "//     (l0..l17). A reorder between the two stages is mandatory.",
        "//   * rope cos comes BEFORE sin in backbone and action_expert inputs, but",
        "//     token_emb emits sin BEFORE cos. Another mandatory swap.",
        "#ifndef QRB_ROS_VLA__PI05_GRAPH_ORDER_HPP_",
        "#define QRB_ROS_VLA__PI05_GRAPH_ORDER_HPP_",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace qrb_ros_vla",
        "{",
        "namespace pi05",
        "{",
        "",
        "struct TensorSpec",
        "{",
        "  const char * name;",
        "  size_t elem_count;",
        "  size_t byte_count;",
        "};",
        "",
    ]

    for comp in COMPONENTS:
        info = parsed[comp]
        for which in ("inputs", "outputs"):
            arr = info[which]
            total = sum(t[4] for t in arr)
            lines.append(f"// {info['name']} {which}: {len(arr)} tensors, {total} bytes total")
            lines.append(f"inline constexpr TensorSpec k{_camel(comp)}{which.capitalize()}[] = {{")
            for name, dims, dtype, count, nbytes in arr:
                dim_str = "x".join(str(d) for d in dims)
                lines.append(
                    f'  {{"{name}", {count}, {nbytes}}},  // [{dim_str}] {dtype.replace("QNN_DATATYPE_", "")}'
                )
            lines.append("};")
            lines.append(
                f"inline constexpr size_t k{_camel(comp)}{which.capitalize()}Bytes = {total};"
            )
            lines.append("")

    lines += [
        "}  // namespace pi05",
        "}  // namespace qrb_ros_vla",
        "",
        "#endif  // QRB_ROS_VLA__PI05_GRAPH_ORDER_HPP_",
        "",
    ]

    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text("\n".join(lines))

    for comp in COMPONENTS:
        info = parsed[comp]
        print(
            f"  {info['name']}: {len(info['inputs'])} in "
            f"({sum(t[4] for t in info['inputs'])} B) / "
            f"{len(info['outputs'])} out ({sum(t[4] for t in info['outputs'])} B)"
        )
    print(f"done: wrote {dst}")
    return 0


def _camel(snake: str) -> str:
    return "".join(part.capitalize() for part in snake.split("_"))


if __name__ == "__main__":
    sys.exit(main())
