name: Comment on Stale Issues
on:
    schedule:
      - cron: '30 1 * * *'
  
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
            days-before-close: -1
            days-before-issue-stale: 30
            days-before-pr-stale: 30
            stale-pr-message: "This PR is stale. Add a nice message, can mention maintainers or maintainer team to draw attention"
            stale-issue-message: "This issue is stale. Add a nice message, can mention maintainers or maintainer team to draw attention"
            